######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 15 14:14:29 2012
######################################################################

QT += core gui

TEMPLATE = app
TARGET = regexinator
DEPENDPATH += . ui
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    samplehighlighter.h
FORMS += ui/mainwindow.ui
SOURCES += \
    mainwindow.cpp \
    main.cpp \
    samplehighlighter.cpp

FORMS += \
    ui/mainwindow.ui
